### ISSUE TITLE
Sonarcloud is not working correctly

### ISSUE THREAD

**Issue by dannoe** [KeeTrayTOTP/KeeTrayTOTP#127]
The [dashboard](https://sonarcloud.io/dashboard?id=KeeTrayTOTP_KeeTrayTOTP) says:

![grafik](https://user-images.githubusercontent.com/7450586/79732290-fef65e00-82e2-11ea-8905-ee498f02a5b9.png)

**Comment by robinvanpoppel** [comment]
Had it in my head already, but better to track with an issue. I was playing around a bit, but for the C# scanning I need to do some additional work in the build.

**Comment by robinvanpoppel** [comment]
Sonarcloud is now running on the Pre-Release (so that master is populated), and on PR's, but this still needs some tweaking.

Some thoughts:
* [ ] The master builds are running in a "ReleasePlgx" target, and are not running tests or code coverage. I'm thinking of having a a separate build for SonarQube, that can run on master and on all the PR's, and would not affect the plgx / release process. For PR's I think it's fine to fail the checks, but not once something is in master.
